sudo: false

language: perl
perl:
    - "5.8"
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
    - "5.22"
    - "5.24"
    - "5.26"

env:
    - NO_DEVEL_COVER=0

matrix:
    include:
        - perl: 5.8
          env: NO_DEVEL_COVER=1

before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init --auto

install:
    - cpanm --quiet --installdeps --notest .
    - if [ "$NO_DEVEL_COVER" = "0" ] && cpanm --quiet --notest Devel::Cover
    - if [ "$NO_DEVEL_COVER" = "0" ] && cpanm --quiet --notest Devel::Cover::Report::Coveralls

script:
    - if [ "$NO_DEVEL_COVER" = "0" ] && cover -delete && cover -test
    - if [ "$NO_DEVEL_COVER" = "1" ] && perl Makefile.PL && make test

after_success:
    - if [ "$NO_DEVEL_COVER" = "0" ] cover -report coveralls
