sudo: false

language: perl
perl:
    - "5.8"
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
    - "5.22"
    - "5.24"
    - "5.26"

matrix:
    include:
        - perl: 5.8
          env: NO_DEVEL_COVER=1

before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init --auto

install:
    - cpanm --quiet --installdeps --notest .
    - [ "$NO_DEVEL_COVER" != "1" ] && cpanm --quiet --notest Devel::Cover
    - [ "$NO_DEVEL_COVER" != "1" ] && cpanm --quiet --notest Devel::Cover::Report::Coveralls

script:
    - [ "$NO_DEVEL_COVER" != "1" ] && cover -delete && cover -test
    - [ "$NO_DEVEL_COVER"  = "1" ] && perl Makefile.PL && make test

after_success:
    - if [ ] cover -report coveralls
